### ISSUE TITLE
VerifyError: com/manuelmaly/hn/MainActivity

### ISSUE THREAD

**Issue by lingling-fan** [manmal/hn-android#185]
//package name: com.manuelmaly.hn
//version: 1.9.15
//target sdk version: android-18
 java.lang.VerifyError: com/manuelmaly/hn/MainActivity
 	at java.lang.Class.newInstanceImpl(Native Method)
 	at java.lang.Class.newInstance(Class.java:1130)
 	at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2128)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by manmal** [comment]
Closing this because the issue hasn't re-occurred.
